-- MySQL Script generated by MySQL Workbench
-- Tue Apr 25 20:10:58 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema av_service
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema av_service
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `av_service` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `av_service` ;

-- -----------------------------------------------------
-- Table `av_service`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `av_service`.`roles` (
  `role_id` INT NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 35
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `av_service`.`persons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `av_service`.`persons` (
  `person_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(100) NOT NULL,
  `phone` VARCHAR(10) NOT NULL,
  `pwd` VARCHAR(100) NOT NULL,
  `role_id` INT NOT NULL,
  `age` VARCHAR(3) NULL DEFAULT NULL,
  `date_of_birth` DATE NULL DEFAULT NULL,
  `gender` VARCHAR(1) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `created_by` VARCHAR(50) NOT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_by` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`person_id`),
  INDEX `role_id` (`role_id` ASC) VISIBLE,
  INDEX `idx_persons_person_id` (`person_id` ASC) VISIBLE,
  CONSTRAINT `persons_ibfk_2`
    FOREIGN KEY (`role_id`)
    REFERENCES `av_service`.`roles` (`role_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `av_service`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `av_service`.`address` (
  `address_id` INT NOT NULL AUTO_INCREMENT,
  `address1` VARCHAR(200) NULL DEFAULT NULL,
  `address2` VARCHAR(200) NULL DEFAULT NULL,
  `city` VARCHAR(50) NULL DEFAULT NULL,
  `state` VARCHAR(50) NULL DEFAULT NULL,
  `zip_code` INT NULL DEFAULT NULL,
  PRIMARY KEY (`address_id`),
  CONSTRAINT `fk_address_person`
    FOREIGN KEY (`address_id`)
    REFERENCES `av_service`.`persons` (`person_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 30
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `av_service`.`contact_msg`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `av_service`.`contact_msg` (
  `contact_id` INT NOT NULL AUTO_INCREMENT,
  `person_id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `mobile_num` VARCHAR(10) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `subject` VARCHAR(100) NOT NULL,
  `message` VARCHAR(500) NOT NULL,
  `status` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`contact_id`),
  INDEX `person_id` (`person_id` ASC) VISIBLE,
  CONSTRAINT `contact_msg_ibfk_1`
    FOREIGN KEY (`person_id`)
    REFERENCES `av_service`.`persons` (`person_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `av_service`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `av_service`.`customers` (
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`customer_id`),
  CONSTRAINT `fk_customers_persons`
    FOREIGN KEY (`customer_id`)
    REFERENCES `av_service`.`persons` (`person_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `av_service`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `av_service`.`employees` (
  `employee_id` INT NOT NULL AUTO_INCREMENT,
  `person_id` INT NOT NULL,
  `job_title` VARCHAR(50) NOT NULL,
  `salary` INT NOT NULL,
  `hire_date` DATE NOT NULL,
  `department_id` INT NOT NULL,
  PRIMARY KEY (`employee_id`),
  INDEX `person_id` (`person_id` ASC) VISIBLE,
  CONSTRAINT `employees_ibfk_1`
    FOREIGN KEY (`person_id`)
    REFERENCES `av_service`.`persons` (`person_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `av_service`.`services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `av_service`.`services` (
  `service_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `unit_price` INT NOT NULL,
  `image` LONGBLOB NULL DEFAULT NULL,
  `message` TEXT NULL DEFAULT NULL,
  `category` VARCHAR(255) NOT NULL,
  `seller_id` INT UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`service_id`),
  INDEX `fk_seller_id` (`seller_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `av_service`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `av_service`.`orders` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  `booked_date` DATE NOT NULL,
  `status` VARCHAR(10) NOT NULL,
  `comments` VARCHAR(255) NULL DEFAULT NULL,
  `confirm_date` DATE NULL DEFAULT NULL,
  `service_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `fk_service_id` (`service_id` ASC) VISIBLE,
  CONSTRAINT `fk_service_id`
    FOREIGN KEY (`service_id`)
    REFERENCES `av_service`.`services` (`service_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `av_service`.`payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `av_service`.`payments` (
  `payment_id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  `date` DATE NOT NULL,
  `amount` INT NOT NULL,
  `payment_method` VARCHAR(10) NOT NULL,
  `order_id` INT NOT NULL,
  PRIMARY KEY (`payment_id`),
  INDEX `customer_id` (`customer_id` ASC) VISIBLE,
  INDEX `order_id` (`order_id` ASC) VISIBLE,
  CONSTRAINT `payments_ibfk_1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `av_service`.`customers` (`customer_id`),
  CONSTRAINT `payments_ibfk_3`
    FOREIGN KEY (`order_id`)
    REFERENCES `av_service`.`orders` (`order_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `av_service`.`sellers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `av_service`.`sellers` (
  `seller_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`seller_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
